sudo: false
language: python

notifications:
  email: false

env:
  - PYTHONDONTWRITEBYTECODE=1

python:
  - "2.7"
  # - "3.5"

install:
  - pip install ${PIP_OPTS} pytest
  - pip install ${PIP_OPTS} pytest-cov
  - pip install ${PIP_OPTS} codecov

script:
  - pip install --editable .
  - make test-all-with-coverage

after_success:
  - codecov
